In [1]:
import numpy as np

np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [2]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.ones_like([1,2,3,4,5])

array([1, 1, 1, 1, 1])

In [5]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
np.arange(1, 11).reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
np.ones_like([[1,2],[3,4]])

array([[1, 1],
       [1, 1]])

In [9]:
np.ones_like([1,2,3,4])

array([1, 1, 1, 1])

In [11]:
a = np.arange(25).reshape(5, 5)
a[0]

array([0, 1, 2, 3, 4])

In [12]:
a = 2
b = np.array([1,2,3,4,5])
a + b

array([3, 4, 5, 6, 7])

In [13]:
a = np.arange(1, 10)
a.sum()

np.int64(45)

In [14]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])